logging:
  config: classpath:logback.xml
  level:
    com.summer.tools.mybatisplus.orm: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://1.15.132.121:7003/postgres?useAffectedRows=true&currentSchema=public
    username: postgres
    password: admin
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://1.15.132.121:7004/flowable-my?serverTimezone=Asia/Shanghai&&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: root
#    password: 123456
    druid:
      max-active: 100
      validation-query: select 1
      filters: stat, wall
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
        exclusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*"
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
      stat-view-servlet:
        enabled: true
        reset-enable: true
        login-username: admin
        login-password: admin
        url-pattern: /druid/*

    redis:
      database: 2
      host: 172.21.11.140
      port: 8064
      password: Qq11
      pool:
        max-active: 30
        max-idle: 30
        min-idle: 5
        max-wait: 30000

template:
  enable: true


# mybatis 配置
mybatis-plus:
  mapperLocations: classpath:/mapper/*.xml
  typeAliasesPackage: com.springboot.template.orm.model
  global-config:
    db-config:
      # 主键类型
      idType: AUTO
      # 增删改字段策略
      insertStrategy: NOT_NULL
      updateStrategy: NOT_NULL
      # 表名是否使用驼峰转下划线命名,只对表名生效
      tableUnderline: true
      # 大写命名,对表名和字段名均生效
      capitalMode: false
      #逻辑删除配置
      logicDeleteField: is_del
      logicDeleteValue: 1
      logicNotDeleteValue: 0
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl