logging:
  config: classpath:logback.xml
  level:
    com.summer.tools.mybatisplus.orm: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://1.15.132.121:7003/postgres?useAffectedRows=true&currentSchema=public
#    username: postgres
#    password: admin

    dynamic:
      primary: pgSql
      datasource:
        pgSql:
          driver-class-name: org.postgresql.Driver
          url: encrypt:aKdMv/OTp0pF6sNyYFd4+Jx6W3uyzMaSh5jTTMN2jmx/1yjW8ho89i9QYp9Zv/zX47kXDN9WLE+PCkbnAgAgtvuaWUBKRvGGi3hbjZ6IeBLXc5gngdYU/ljkC0C5KPIY
          username: encrypt:mRJiAObRQ86L5Pfo+lmsVQ==
          password: encrypt:rfWFZu1q/SQFmaqMKmphJw==
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: encrypt:IJpNXqe+5RtPSb+/rCuqzS5d0J1ZF5GdazE5EKW3thXaTWYEusQOSsHy7QUJAu7jZwTtZfONsgDq6sQ3lygxbkVBG/jcY9Ry7oo6JC3Yl9erMZecbP7opuA1hbtm0qdYfHQL88f7NamQb9kS3AVgUh+zuh2GTYrzWotvzgQtdsQYvomwR65ReTd5m/f1u4ju
          username: encrypt:Ck/Pyuq4uHEWt9yQg+4wbw==
          password: encrypt:dQcSO4Z5iULoFru3T1v5Tg==
    druid:
      max-active: 100
      validation-query: select 1
      filters: stat, wall
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
        exclusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*"
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
      stat-view-servlet:
        enabled: true
        reset-enable: true
        login-username: admin
        login-password: admin
        url-pattern: /druid/*

  main:
    allow-bean-definition-overriding: true
tenant:
  enable: true
  service: dao


# mybatis 配置
mybatis-plus:
  mapperLocations: classpath:/mapper/*.xml
  typeAliasesPackage: com.springboot.template.orm.model
  global-config:
    db-config:
      # 主键类型
      idType: AUTO
      # 增删改字段策略
      insertStrategy: NOT_NULL
      updateStrategy: NOT_NULL
      # 表名是否使用驼峰转下划线命名,只对表名生效
      tableUnderline: true
      # 大写命名,对表名和字段名均生效
      capitalMode: false
      #逻辑删除配置
      logicDeleteField: is_del
      logicDeleteValue: 1
      logicNotDeleteValue: 0
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl