server:
  tomcat:
    uri-encoding: UTF-8
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  profiles:
    active: dev, common
  application:
    name: template

