server:
  tomcat:
    uri-encoding: UTF-8
  port: 83
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  profiles:
    active: dev
  application:
    name: flowable-all

