logging:
  config: classpath:logback.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.132.121:7004/summer-tools?serverTimezone=Asia/Shanghai&&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
#  security:
#    oauth2:
#      client:
#        registration:
#          git:
#            client-id: GlimmerForest
#            client-secret: 1377241qaz@WSX3edc$RFV
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# mybatis 配置
mybatis-plus:
  mapperLocations: classpath:/mapper/*.xml
  typeAliasesPackage: com.springboot.template.orm.model
  global-config:
    db-config:
      # 主键类型
      idType: AUTO
      # 增删改字段策略
      insertStrategy: NOT_NULL
      updateStrategy: NOT_NULL
      # 表名是否使用驼峰转下划线命名,只对表名生效
      tableUnderline: true
      # 大写命名,对表名和字段名均生效
      capitalMode: false
      #逻辑删除配置
      logicDeleteField: is_del
      logicDeleteValue: 1
      logicNotDeleteValue: 0
