logging:
  config: classpath:logback.xml


common:
  encrypt:
    enable: true
    secretKey: boss567890encode
    encoding: UTF-8
  ftp:
    host: ""
    port: 22
    user: root
    password: ""
    secure: true

  cloud-storage:
      accountName: johnwang
      accountKey:
      endPoint: core.windows.net
      protocol: https
      containerName: test
      baseUrl: https://johnwang.blob.core.windows.net/test
      type:  #azure # azure 微软云

  swagger:
    basePackage: com.summer.tools
    description: 项目接口文档url (http://localhost[:port]/doc.html)
    globalParams:
      - name: token
        paramType: header
        javaType: string
        description: 支持 jwt token
      - name: requestId
        paramType: header
        javaType: string
        description: 请求唯一标识

knife4j:
  enable: true
  basic:
    username: admin
    password: test
    enable: true